apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - ../../base

patchesStrategicMerge:
  - replicas-patch.yaml
  - strategy-patch.yaml
  - ingress-patch.yaml

images:
  - name: <ECR_REGISTRY>/auth-service
    newName: riyaji/auth-service
    newTag: dev
  - name: <ECR_REGISTRY>/stock-service
    newName: riyaji/stock-service
    newTag: dev
  - name: <ECR_REGISTRY>/whatsapp-connector-service
    newName: riyaji/whatsapp-connector-service
    newTag: dev
  - name: <ECR_REGISTRY>/ai-orchestrator-service
    newName: riyaji/ai-orchestrator-service
    newTag: dev
  - name: <ECR_REGISTRY>/notification-service
    newName: riyaji/notification-service
    newTag: dev
  - name: <ECR_REGISTRY>/file-storage-service
    newName: riyaji/file-storage-service
    newTag: dev

secretGenerator:
  - name: platform-secrets
    envs:
      - secrets.env
    options:
      disableNameSuffixHash: true
