apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - ../../k8s/base

images:
  - name: <ECR_REGISTRY>/auth-service
    newName: ${ECR_REGISTRY}/auth-service
    newTag: ${IMAGE_TAG}
  - name: <ECR_REGISTRY>/stock-service
    newName: ${ECR_REGISTRY}/stock-service
    newTag: ${IMAGE_TAG}
  - name: <ECR_REGISTRY>/whatsapp-connector-service
    newName: ${ECR_REGISTRY}/whatsapp-connector-service
    newTag: ${IMAGE_TAG}
  - name: <ECR_REGISTRY>/ai-orchestrator-service
    newName: ${ECR_REGISTRY}/ai-orchestrator-service
    newTag: ${IMAGE_TAG}
  - name: <ECR_REGISTRY>/notification-service
    newName: ${ECR_REGISTRY}/notification-service
    newTag: ${IMAGE_TAG}
  - name: <ECR_REGISTRY>/file-storage-service
    newName: ${ECR_REGISTRY}/file-storage-service
    newTag: ${IMAGE_TAG}

secretGenerator:
  - name: platform-secrets
    literals:
      - rabbitmq_url=${RABBITMQ_URL}
      - stock_database_url=${STOCK_DATABASE_URL}
      - whatsapp_database_url=${WHATSAPP_DATABASE_URL}
      - ai_database_url=${AI_DATABASE_URL}
      - gemini_api_key=${GEMINI_API_KEY}
      - groq_api_key=${GROQ_API_KEY}
