apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: products-ingress
  namespace: ecommerce
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: ecommerce-products-strip@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - products.ecomaiselleragent.store
      secretName: products-ecomaiselleragent-store-tls
  rules:
    - host: products.ecomaiselleragent.store
      http:
        paths:
          - path: /api/v1/products
            pathType: Prefix
            backend:
              service:
                name: stock-service
                port:
                  number: 8001
