apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  # Default username "user"
  RABBITMQ_DEFAULT_USER: dXNlcg==
  # Default password "password" - CHANGE THIS
  RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ=
